### PR TITLE
added test

### PR DESCRIPTION
**Pull request by PREETI2000**
## Summary by CodeRabbit

- **New Features**
	- Introduced configuration files (`config.yaml` and `coderabbit.yaml`) to enforce best practices and project structure for Django applications.
	- Added several test functions to enhance testing capabilities for user notes and rewards.

- **Bug Fixes**
	- Updated the `SECRET_KEY` in settings for improved security.

- **Documentation**
	- Added detailed rules and best practices in configuration files to guide developers in maintaining code quality.

### CODE REVIEW

**Comment by PREETI2000** [comment]
@coderabbit.ai review

**Comment by preetibhandiwad** [comment]
@coderabbit.ai review

**Comment by preetibhandiwad** [comment]
@coderabbit.ai review

**Comment by preetibhandiwad** [comment]
@coderabbit.ai review

**Pull request merged**
